import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

describe("автовыкладка Beget", () => {
  it("вотчер не дублирует сборку и читает обе метки", () => {
    const watch = readFileSync(new URL("./beget-watch.mjs", import.meta.url), "utf8");
    const sh = readFileSync(new URL("./beget-deploy.sh", import.meta.url), "utf8");
    assert.match(watch, /lockHeld/);
    assert.match(watch, /\.deploy-rev/);
    assert.match(watch, /сборка уже идёт/);
    assert.match(sh, /ROOT\/\.deploy-rev/);
    assert.match(sh, /exit 0/);
    assert.match(watch, /RA_DEPLOY_BG/);
    assert.match(sh, /status.*online/);
    assert.doesNotMatch(sh, /pm2 restart rastudio-deploy --update-env/);
    assert.match(watch, /INTERVAL_MS = 8_000/);
    assert.match(watch, /каждые 8 с/);
    assert.match(watch, /return lockHeld\(\)/);
    assert.doesNotMatch(watch, /\.build-stage", "package\.json"\)/);
    assert.match(sh, /fail_cleanup/);
    assert.match(sh, /3000 уже слушает/);
    assert.match(sh, /rm -f "\$LOCK"/);
    assert.match(sh, /RA_DEPLOY_INNER/);
    assert.match(sh, /сборка отвязана/);
    assert.match(sh, /keep_lock_fresh/);
    assert.match(sh, /2700/);
    assert.match(watch, /45 \* 60 \* 1000/);
    assert.doesNotMatch(watch, /timeout: 20 \* 60 \* 1000/);
    assert.match(watch, /crm-history-restart.wanted/);
    assert.match(watch, /maybeRestartHistory/);
    assert.match(watch, /workerAlive/);
    assert.match(watch, /lockAlive/);
    assert.doesNotMatch(watch, /история ещё занята/);
    assert.match(sh, /crm-history-restart.wanted/);
    assert.match(sh, /restart_or_defer_history/);
    assert.match(sh, /workerAlive/);
    assert.match(sh, /lockAlive/);
  });
});
