/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ApiAgentChannelRouteImport } from './routes/api/agent.$channel'
import { Route as ApiPayYookassaRouteImport } from './routes/api/pay.yookassa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChannelRoute = ApiAgentChannelRouteImport.update({
  id: '/api/agent/$channel',
  path: '/api/agent/$channel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayYookassaRoute = ApiPayYookassaRouteImport.update({
  id: '/api/pay/yookassa',
  path: '/api/pay/yookassa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/pay': typeof PayRoute
  '/schedule': typeof ScheduleRoute
  '/api/agent/$channel': typeof ApiAgentChannelRoute
  '/api/pay/yookassa': typeof ApiPayYookassaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/pay': typeof PayRoute
  '/schedule': typeof ScheduleRoute
  '/api/agent/$channel': typeof ApiAgentChannelRoute
  '/api/pay/yookassa': typeof ApiPayYookassaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/pay': typeof PayRoute
  '/schedule': typeof ScheduleRoute
  '/api/agent/$channel': typeof ApiAgentChannelRoute
  '/api/pay/yookassa': typeof ApiPayYookassaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/pay'
    | '/schedule'
    | '/api/agent/$channel'
    | '/api/pay/yookassa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/pay'
    | '/schedule'
    | '/api/agent/$channel'
    | '/api/pay/yookassa'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/pay'
    | '/schedule'
    | '/api/agent/$channel'
    | '/api/pay/yookassa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  PayRoute: typeof PayRoute
  ScheduleRoute: typeof ScheduleRoute
  ApiAgentChannelRoute: typeof ApiAgentChannelRoute
  ApiPayYookassaRoute: typeof ApiPayYookassaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/$channel': {
      id: '/api/agent/$channel'
      path: '/api/agent/$channel'
      fullPath: '/api/agent/$channel'
      preLoaderRoute: typeof ApiAgentChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/yookassa': {
      id: '/api/pay/yookassa'
      path: '/api/pay/yookassa'
      fullPath: '/api/pay/yookassa'
      preLoaderRoute: typeof ApiPayYookassaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  PayRoute: PayRoute,
  ScheduleRoute: ScheduleRoute,
  ApiAgentChannelRoute: ApiAgentChannelRoute,
  ApiPayYookassaRoute: ApiPayYookassaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
